version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
  node: circleci/node@4.2.0
workflows:
  deploy:
    jobs:
      # Deployment to staging occurs on the main branch
      - heroku/deploy-via-git:
          api-key: STAGING_HEROKU_API_KEY
          app-name: $STAGING_HEROKU_APP_NAME
          filters:
            branches:
              only: main
      # Deployment to production occurs on the prod branch
      - heroku/deploy-via-git:
          api-key: PROD_HEROKU_API_KEY
          app-name: $PROD_HEROKU_APP_NAME
          filters:
            branches:
              only: prod
